In [77]:
import tensorflow as tf
import cv2
import numpy as np
import os

In [129]:
def getFlatImg(fileName):
    # list all the pictures under that directory
    fruitPics = os.listdir(fileName)
    allFruitPics = []
    for fruitPic in fruitPics:
        img = cv2.imread(os.path.join(fileName, fruitPic))
        img = img.flatten()
        img = img.reshape((1, img.shape[0]))
        allFruitPics.append(img)   
    allFruitPics = np.vstack(allFruitPics)
    return allFruitPics

def getImg(imgType):
    fruitTypes = os.listdir(imgType)
    fruitTypes = [fruit for fruit in fruitTypes if fruit[0] != '.']
    count = 0
    inputs = []
    outputs = []
    for fruitType in fruitTypes:
        # for the 25 fruit types
        fruitInput = getFlatImg(os.path.join(imgType, fruitType))
        inputs.append(fruitInput)
        fruitOutput = np.ones((fruitInput.shape[0], 1)) * count
        outputs.append(fruitOutput)
        count += 1
    inputs = np.vstack(inputs)
    outputs = np.vstack(outputs)
    print(inputs)
    print(outputs)
    
def getTrainingImg():
    return getImg('fruits-360/Training/')
    
def getTestingImg():
    return getImg('fruits-350/Testing/')

In [130]:
getTrainingImg()

[[255 254 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 254 255 ... 255 255 255]
 ...
 [255 255 254 ... 255 255 255]
 [250 255 251 ... 255 255 255]
 [251 255 247 ... 255 255 255]]
[[ 0.]
 [ 0.]
 [ 0.]
 ...
 [24.]
 [24.]
 [24.]]
